version: '3'

services:
  auth-api:
    build: .
    container_name: auth-api
    ports:
      - 8082:80
    depends_on:
        - auth-api-database
    environment:
        # - DB_PASSWORD=example
        # - DB_auth=root
        - DB_HOST=auth-api-database
        - DB_DATABASE=auth
    volumes:
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./config:/var/www/config
      - ./public:/var/www/public
      - ./phpunit.xml:/var/www/phpunit.xml:ro
      - ./phpcs.xml:/var/www/phpcs.xml:ro

  auth-api-database:
    image: mongo
    container_name: auth-api-database
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_authNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  test:
    build: .
    container_name: auth-api-test
    depends_on:
        - auth-api-database
    environment:
        # - DB_PASSWORD=example
        # - DB_auth=root
        - DB_HOST=auth-api-database
        - DB_DATABASE=api
    volumes:
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./config:/var/www/config
      - ./public:/var/www/public
      - ./phpunit.xml:/var/www/phpunit.xml:ro
      - ./phpcs.xml:/var/www/phpcs.xml:ro
    command: ./vendor/bin/phpunit
