version: '3'

services:
  auth-api:
    build:
      context: .
      args:
        - ENV=development
    container_name: auth-api
    ports:
      - 8082:80
    depends_on:
        - auth-api-database
    environment:
        - DB_HOST=auth-api-database
        - DB_DATABASE=auth
        - JWT_SECRET=thisissomesecretornot
    volumes:
      - ./src:/var/www/src
      - ./config:/var/www/config
      - ./public:/var/www/public

  auth-api-database:
    image: mongo
    container_name: auth-api-database
    restart: always

  test:
    build:
      context: .
      args:
        - ENV=development
    container_name: auth-api-test
    depends_on:
        - auth-api-database
    environment:
        - DB_HOST=auth-api-database
        - DB_DATABASE=test-auth
    volumes:
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./config:/var/www/config
      - ./public:/var/www/public
      - ./phpunit.xml:/var/www/phpunit.xml:ro
      - ./phpcs.xml:/var/www/phpcs.xml:ro
    command: bash -c "./vendor/bin/phpunit && ./vendor/bin/phpcs --standard=./phpcs.xml ./src"
    # command: bash -c "./vendor/bin/phpunit --coverage-html ./tests/doc && ./vendor/bin/phpcs --standard=./phpcs.xml ./src"
